/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPayrollRouteImport } from './routes/app.payroll'
import { Route as AppPreferencesRouteImport } from './routes/app.preferences'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppAdminApprovalsRouteImport } from './routes/app.admin.approvals'
import { Route as AppAdminCoverageRouteImport } from './routes/app.admin.coverage'
import { Route as AppAdminEmployeesRouteImport } from './routes/app.admin.employees'
import { Route as AppAdminLocationsRouteImport } from './routes/app.admin.locations'
import { Route as AppAdminPayrollRouteImport } from './routes/app.admin.payroll'
import { Route as AppAdminSchedulerRouteImport } from './routes/app.admin.scheduler'
import { Route as AppAdminSchedulesRouteImport } from './routes/app.admin.schedules'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminEmployeesIndexRouteImport } from './routes/app.admin.employees.index'
import { Route as AppAdminEmployeesIdRouteImport } from './routes/app.admin.employees.$id'
import { Route as AppAdminEmployeesNewRouteImport } from './routes/app.admin.employees.new'
import { Route as AppAdminPayrollIndexRouteImport } from './routes/app.admin.payroll.index'
import { Route as AppAdminPayrollEmployeeIdRouteImport } from './routes/app.admin.payroll.$employeeId'
import { Route as AppAdminSchedulesIndexRouteImport } from './routes/app.admin.schedules.index'
import { Route as AppAdminSchedulesIdRouteImport } from './routes/app.admin.schedules.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferencesRoute = AppPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCoverageRoute = AppAdminCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmployeesRoute = AppAdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLocationsRoute = AppAdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPayrollRoute = AppAdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSchedulerRoute = AppAdminSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSchedulesRoute = AppAdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmployeesIndexRoute = AppAdminEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminEmployeesRoute,
} as any)
const AppAdminEmployeesIdRoute = AppAdminEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminEmployeesRoute,
} as any)
const AppAdminEmployeesNewRoute = AppAdminEmployeesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAdminEmployeesRoute,
} as any)
const AppAdminPayrollIndexRoute = AppAdminPayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminPayrollRoute,
} as any)
const AppAdminPayrollEmployeeIdRoute =
  AppAdminPayrollEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AppAdminPayrollRoute,
  } as any)
const AppAdminSchedulesIndexRoute = AppAdminSchedulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminSchedulesRoute,
} as any)
const AppAdminSchedulesIdRoute = AppAdminSchedulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminSchedulesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/coverage': typeof AppAdminCoverageRoute
  '/app/admin/employees': typeof AppAdminEmployeesRouteWithChildren
  '/app/admin/locations': typeof AppAdminLocationsRoute
  '/app/admin/payroll': typeof AppAdminPayrollRouteWithChildren
  '/app/admin/scheduler': typeof AppAdminSchedulerRoute
  '/app/admin/schedules': typeof AppAdminSchedulesRouteWithChildren
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/employees/$id': typeof AppAdminEmployeesIdRoute
  '/app/admin/employees/new': typeof AppAdminEmployeesNewRoute
  '/app/admin/payroll/$employeeId': typeof AppAdminPayrollEmployeeIdRoute
  '/app/admin/schedules/$id': typeof AppAdminSchedulesIdRoute
  '/app/admin/employees/': typeof AppAdminEmployeesIndexRoute
  '/app/admin/payroll/': typeof AppAdminPayrollIndexRoute
  '/app/admin/schedules/': typeof AppAdminSchedulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/coverage': typeof AppAdminCoverageRoute
  '/app/admin/locations': typeof AppAdminLocationsRoute
  '/app/admin/scheduler': typeof AppAdminSchedulerRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/employees/$id': typeof AppAdminEmployeesIdRoute
  '/app/admin/employees/new': typeof AppAdminEmployeesNewRoute
  '/app/admin/payroll/$employeeId': typeof AppAdminPayrollEmployeeIdRoute
  '/app/admin/schedules/$id': typeof AppAdminSchedulesIdRoute
  '/app/admin/employees': typeof AppAdminEmployeesIndexRoute
  '/app/admin/payroll': typeof AppAdminPayrollIndexRoute
  '/app/admin/schedules': typeof AppAdminSchedulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/coverage': typeof AppAdminCoverageRoute
  '/app/admin/employees': typeof AppAdminEmployeesRouteWithChildren
  '/app/admin/locations': typeof AppAdminLocationsRoute
  '/app/admin/payroll': typeof AppAdminPayrollRouteWithChildren
  '/app/admin/scheduler': typeof AppAdminSchedulerRoute
  '/app/admin/schedules': typeof AppAdminSchedulesRouteWithChildren
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/employees/$id': typeof AppAdminEmployeesIdRoute
  '/app/admin/employees/new': typeof AppAdminEmployeesNewRoute
  '/app/admin/payroll/$employeeId': typeof AppAdminPayrollEmployeeIdRoute
  '/app/admin/schedules/$id': typeof AppAdminSchedulesIdRoute
  '/app/admin/employees/': typeof AppAdminEmployeesIndexRoute
  '/app/admin/payroll/': typeof AppAdminPayrollIndexRoute
  '/app/admin/schedules/': typeof AppAdminSchedulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/ai'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/preferences'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/app/'
    | '/app/admin/approvals'
    | '/app/admin/coverage'
    | '/app/admin/employees'
    | '/app/admin/locations'
    | '/app/admin/payroll'
    | '/app/admin/scheduler'
    | '/app/admin/schedules'
    | '/app/admin/users'
    | '/app/admin/employees/$id'
    | '/app/admin/employees/new'
    | '/app/admin/payroll/$employeeId'
    | '/app/admin/schedules/$id'
    | '/app/admin/employees/'
    | '/app/admin/payroll/'
    | '/app/admin/schedules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/admin'
    | '/app/ai'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/preferences'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/app'
    | '/app/admin/approvals'
    | '/app/admin/coverage'
    | '/app/admin/locations'
    | '/app/admin/scheduler'
    | '/app/admin/users'
    | '/app/admin/employees/$id'
    | '/app/admin/employees/new'
    | '/app/admin/payroll/$employeeId'
    | '/app/admin/schedules/$id'
    | '/app/admin/employees'
    | '/app/admin/payroll'
    | '/app/admin/schedules'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/ai'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/preferences'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/app/'
    | '/app/admin/approvals'
    | '/app/admin/coverage'
    | '/app/admin/employees'
    | '/app/admin/locations'
    | '/app/admin/payroll'
    | '/app/admin/scheduler'
    | '/app/admin/schedules'
    | '/app/admin/users'
    | '/app/admin/employees/$id'
    | '/app/admin/employees/new'
    | '/app/admin/payroll/$employeeId'
    | '/app/admin/schedules/$id'
    | '/app/admin/employees/'
    | '/app/admin/payroll/'
    | '/app/admin/schedules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preferences': {
      id: '/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AppPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/approvals': {
      id: '/app/admin/approvals'
      path: '/approvals'
      fullPath: '/app/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/coverage': {
      id: '/app/admin/coverage'
      path: '/coverage'
      fullPath: '/app/admin/coverage'
      preLoaderRoute: typeof AppAdminCoverageRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/employees': {
      id: '/app/admin/employees'
      path: '/employees'
      fullPath: '/app/admin/employees'
      preLoaderRoute: typeof AppAdminEmployeesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/locations': {
      id: '/app/admin/locations'
      path: '/locations'
      fullPath: '/app/admin/locations'
      preLoaderRoute: typeof AppAdminLocationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/payroll': {
      id: '/app/admin/payroll'
      path: '/payroll'
      fullPath: '/app/admin/payroll'
      preLoaderRoute: typeof AppAdminPayrollRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/scheduler': {
      id: '/app/admin/scheduler'
      path: '/scheduler'
      fullPath: '/app/admin/scheduler'
      preLoaderRoute: typeof AppAdminSchedulerRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/schedules': {
      id: '/app/admin/schedules'
      path: '/schedules'
      fullPath: '/app/admin/schedules'
      preLoaderRoute: typeof AppAdminSchedulesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/employees/': {
      id: '/app/admin/employees/'
      path: '/'
      fullPath: '/app/admin/employees/'
      preLoaderRoute: typeof AppAdminEmployeesIndexRouteImport
      parentRoute: typeof AppAdminEmployeesRoute
    }
    '/app/admin/employees/$id': {
      id: '/app/admin/employees/$id'
      path: '/$id'
      fullPath: '/app/admin/employees/$id'
      preLoaderRoute: typeof AppAdminEmployeesIdRouteImport
      parentRoute: typeof AppAdminEmployeesRoute
    }
    '/app/admin/employees/new': {
      id: '/app/admin/employees/new'
      path: '/new'
      fullPath: '/app/admin/employees/new'
      preLoaderRoute: typeof AppAdminEmployeesNewRouteImport
      parentRoute: typeof AppAdminEmployeesRoute
    }
    '/app/admin/payroll/': {
      id: '/app/admin/payroll/'
      path: '/'
      fullPath: '/app/admin/payroll/'
      preLoaderRoute: typeof AppAdminPayrollIndexRouteImport
      parentRoute: typeof AppAdminPayrollRoute
    }
    '/app/admin/payroll/$employeeId': {
      id: '/app/admin/payroll/$employeeId'
      path: '/$employeeId'
      fullPath: '/app/admin/payroll/$employeeId'
      preLoaderRoute: typeof AppAdminPayrollEmployeeIdRouteImport
      parentRoute: typeof AppAdminPayrollRoute
    }
    '/app/admin/schedules/': {
      id: '/app/admin/schedules/'
      path: '/'
      fullPath: '/app/admin/schedules/'
      preLoaderRoute: typeof AppAdminSchedulesIndexRouteImport
      parentRoute: typeof AppAdminSchedulesRoute
    }
    '/app/admin/schedules/$id': {
      id: '/app/admin/schedules/$id'
      path: '/$id'
      fullPath: '/app/admin/schedules/$id'
      preLoaderRoute: typeof AppAdminSchedulesIdRouteImport
      parentRoute: typeof AppAdminSchedulesRoute
    }
  }
}

interface AppAdminEmployeesRouteChildren {
  AppAdminEmployeesIdRoute: typeof AppAdminEmployeesIdRoute
  AppAdminEmployeesNewRoute: typeof AppAdminEmployeesNewRoute
  AppAdminEmployeesIndexRoute: typeof AppAdminEmployeesIndexRoute
}

const AppAdminEmployeesRouteChildren: AppAdminEmployeesRouteChildren = {
  AppAdminEmployeesIdRoute: AppAdminEmployeesIdRoute,
  AppAdminEmployeesNewRoute: AppAdminEmployeesNewRoute,
  AppAdminEmployeesIndexRoute: AppAdminEmployeesIndexRoute,
}

const AppAdminEmployeesRouteWithChildren =
  AppAdminEmployeesRoute._addFileChildren(AppAdminEmployeesRouteChildren)

interface AppAdminPayrollRouteChildren {
  AppAdminPayrollEmployeeIdRoute: typeof AppAdminPayrollEmployeeIdRoute
  AppAdminPayrollIndexRoute: typeof AppAdminPayrollIndexRoute
}

const AppAdminPayrollRouteChildren: AppAdminPayrollRouteChildren = {
  AppAdminPayrollEmployeeIdRoute: AppAdminPayrollEmployeeIdRoute,
  AppAdminPayrollIndexRoute: AppAdminPayrollIndexRoute,
}

const AppAdminPayrollRouteWithChildren = AppAdminPayrollRoute._addFileChildren(
  AppAdminPayrollRouteChildren,
)

interface AppAdminSchedulesRouteChildren {
  AppAdminSchedulesIdRoute: typeof AppAdminSchedulesIdRoute
  AppAdminSchedulesIndexRoute: typeof AppAdminSchedulesIndexRoute
}

const AppAdminSchedulesRouteChildren: AppAdminSchedulesRouteChildren = {
  AppAdminSchedulesIdRoute: AppAdminSchedulesIdRoute,
  AppAdminSchedulesIndexRoute: AppAdminSchedulesIndexRoute,
}

const AppAdminSchedulesRouteWithChildren =
  AppAdminSchedulesRoute._addFileChildren(AppAdminSchedulesRouteChildren)

interface AppAdminRouteChildren {
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminCoverageRoute: typeof AppAdminCoverageRoute
  AppAdminEmployeesRoute: typeof AppAdminEmployeesRouteWithChildren
  AppAdminLocationsRoute: typeof AppAdminLocationsRoute
  AppAdminPayrollRoute: typeof AppAdminPayrollRouteWithChildren
  AppAdminSchedulerRoute: typeof AppAdminSchedulerRoute
  AppAdminSchedulesRoute: typeof AppAdminSchedulesRouteWithChildren
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminCoverageRoute: AppAdminCoverageRoute,
  AppAdminEmployeesRoute: AppAdminEmployeesRouteWithChildren,
  AppAdminLocationsRoute: AppAdminLocationsRoute,
  AppAdminPayrollRoute: AppAdminPayrollRouteWithChildren,
  AppAdminSchedulerRoute: AppAdminSchedulerRoute,
  AppAdminSchedulesRoute: AppAdminSchedulesRouteWithChildren,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAiRoute: typeof AppAiRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPreferencesRoute: typeof AppPreferencesRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAiRoute: AppAiRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPreferencesRoute: AppPreferencesRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
